services:
  java-secure-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-secure-api
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.java-secure.rule=Host(`trading-java-bot`)"
      - "traefik.http.routers.java-secure.entrypoints=web"
      - "traefik.http.services.java-secure.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true