#include classpath("conf/base.conf")
swagger.access.password = "XXXXXXXXXXXXXXX"

# Binance Lecture
# api.binance.key.public = "XXXXXXXXXXXXXXX"
# api.binance.key.secret = "XXXXXXXXXXXXXXX"

# Binance Lecture & Ecriture
api.binance.key.public = "XXXXXXXXXXXXXXX"
api.binance.key.secret = "XXXXXXXXXXXXXXX"

# SLACK
# Url du channel "XXXXXXXXXXXXXXX"
api.slack.url = "XXXXXXXXXXXXXXX"
api.slack.token = "XXXXXXXXXXXXXXX"

algotithm.crypto.ignore-list.auto-staking = ["BNB"]
algotithm.crypto.ignore-list.redeem-flexible = ["BNB"]

jobs.cron.auto-restack=""
jobs.cron.destack-flexible=""
jobs.cron.redeem-liquidity=""

